import 'dotenv/config';
import { connectDB } from '../config/db.js';
import { Plant } from '../models/Plant.js';

const samplePlants = [
  {
    plantName: 'Tulsi',
    scientificName: 'Ocimum sanctum',
    description: 'Holy Basil - sacred plant known for its medicinal properties',
    uses: 'Immunity, Respiratory health, Stress relief',
    imagePath: 'images/tulsi.jpg',
    category: 'Medicinal',
  },
  {
    plantName: 'Ashwagandha',
    scientificName: 'Withania somnifera',
    description: 'Indian Ginseng - powerful adaptogenic herb',
    uses: 'Stress relief, Energy, Vitality',
    imagePath: 'images/ashwagandha.jpg',
    category: 'Adaptogen',
  },
  {
    plantName: 'Neem',
    scientificName: 'Azadirachta indica',
    description: 'The village pharmacy - natural purifier',
    uses: 'Blood purification, Skin health, Antibacterial',
    imagePath: 'images/neem.jpg',
    category: 'Purifier',
  },
  {
    plantName: 'Brahmi',
    scientificName: 'Bacopa monnieri',
    description: 'Memory enhancer - brain tonic',
    uses: 'Memory, Cognitive function, Mental clarity',
    imagePath: 'images/brahmi.jpg',
    category: 'Brain Tonic',
  },
  {
    plantName: 'Aloe Vera',
    scientificName: 'Aloe barbadensis',
    description: 'Miracle plant - healing gel',
    uses: 'Skin care, Digestive health, Wound healing',
    imagePath: 'images/bg.jpg',
    category: 'Healing',
  },
  {
    plantName: 'Ginger',
    scientificName: 'Zingiber officinale',
    description: 'Universal medicine - digestive aid',
    uses: 'Digestion, Nausea relief, Anti-inflammatory',
    imagePath: 'images/ginger.jpg',
    category: 'Digestive',
  },
  {
    plantName: 'Turmeric',
    scientificName: 'Curcuma longa',
    description: 'Golden spice - natural anti-inflammatory',
    uses: 'Anti-inflammatory, Immunity, Joint health',
    imagePath: 'images/turmeric.jpg',
    category: 'Anti-inflammatory',
  },
  {
    plantName: 'Amla',
    scientificName: 'Phyllanthus emblica',
    description: 'Indian Gooseberry - vitamin C powerhouse',
    uses: 'Immunity, Hair health, Antioxidant',
    imagePath: 'images/1.jpg',
    category: 'Immunity',
  },
  {
    plantName: 'Haritaki',
    scientificName: 'Terminalia chebula',
    description: 'King of medicines - digestive tonic',
    uses: 'Digestion, Detoxification, Rejuvenation',
    imagePath: 'images/2.jpg',
    category: 'Digestive',
  },
  {
    plantName: 'Bibhitaki',
    scientificName: 'Terminalia bellirica',
    description: 'Triphala component - respiratory health',
    uses: 'Respiratory health, Detoxification, Immunity',
    imagePath: 'images/3.jpg',
    category: 'Respiratory',
  },
  {
    plantName: 'Shatavari',
    scientificName: 'Asparagus racemosus',
    description: 'Queen of herbs - women’s health tonic',
    uses: 'Women’s health, Hormonal balance, Vitality',
    imagePath: 'images/4.jpg',
    category: 'Women Health',
  },
  {
    plantName: 'Giloy',
    scientificName: 'Tinospora cordifolia',
    description: 'Divine nectar - immunity booster',
    uses: 'Immunity, Fever, Detoxification',
    imagePath: 'images/5.jpg',
    category: 'Immunity',
  },
  {
    plantName: 'Mulethi',
    scientificName: 'Glycyrrhiza glabra',
    description: 'Licorice - soothing herb',
    uses: 'Respiratory health, Digestive aid, Voice clarity',
    imagePath: 'images/6.jpg',
    category: 'Respiratory',
  },
  {
    plantName: 'Arjuna',
    scientificName: 'Terminalia arjuna',
    description: 'Heart protector - cardiac tonic',
    uses: 'Heart health, Blood pressure, Cardio support',
    imagePath: 'images/7.jpg',
    category: 'Cardiac',
  },
  {
    plantName: 'Shankhpushpi',
    scientificName: 'Convolvulus pluricaulis',
    description: 'Brain tonic - memory enhancer',
    uses: 'Memory, Mental health, Stress relief',
    imagePath: 'images/8.jpg',
    category: 'Brain Tonic',
  },
  {
    plantName: 'Guduchi',
    scientificName: 'Tinospora cordifolia',
    description: 'Amrit - rejuvenating herb',
    uses: 'Immunity, Rejuvenation, Fever management',
    imagePath: 'images/9.jpg',
    category: 'Rejuvenation',
  },
  {
    plantName: 'Guggul',
    scientificName: 'Commiphora wightii',
    description: 'Cholesterol manager - joint health',
    uses: 'Cholesterol, Weight management, Joint health',
    imagePath: 'images/10.jpg',
    category: 'Metabolic',
  },
  {
    plantName: 'Jatamansi',
    scientificName: 'Nardostachys jatamansi',
    description: 'Calming herb - sleep inducer',
    uses: 'Sleep, Anxiety relief, Mental calm',
    imagePath: 'images/11.jpg',
    category: 'Calming',
  },
  {
    plantName: 'Bhringraj',
    scientificName: 'Eclipta alba',
    description: 'King of hair - hair growth tonic',
    uses: 'Hair growth, Liver health, Eyesight',
    imagePath: 'images/12.jpg',
    category: 'Hair Care',
  },
  {
    plantName: 'Punarnava',
    scientificName: 'Boerhavia diffusa',
    description: 'Kidney tonic - rejuvenator',
    uses: 'Kidney health, Urinary system, Rejuvenation',
    imagePath: 'images/13.jpg',
    category: 'Kidney Health',
  },
  {
    plantName: 'Manjistha',
    scientificName: 'Rubia cordifolia',
    description: 'Blood purifier - skin tonic',
    uses: 'Blood purification, Skin health, Detox',
    imagePath: 'images/14.jpg',
    category: 'Purifier',
  },
  {
    plantName: 'Vidanga',
    scientificName: 'Embelia ribes',
    description: 'Antiparasitic - digestive aid',
    uses: 'Antiparasitic, Digestive health, Weight loss',
    imagePath: 'images/15.jpg',
    category: 'Digestive',
  },
  {
    plantName: 'Vacha',
    scientificName: 'Acorus calamus',
    description: 'Memory enhancer - speech clarity',
    uses: 'Memory, Speech, Mental clarity',
    imagePath: 'images/16.jpg',
    category: 'Brain Tonic',
  },
  {
    plantName: 'Pippali',
    scientificName: 'Piper longum',
    description: 'Long pepper - respiratory health',
    uses: 'Respiratory health, Digestion, Immunity',
    imagePath: 'images/17.jpg',
    category: 'Respiratory',
  },
  {
    plantName: 'Kutki',
    scientificName: 'Picrorhiza kurroa',
    description: 'Liver tonic - bitter herb',
    uses: 'Liver health, Detoxification, Immunity',
    imagePath: 'images/18.jpg',
    category: 'Liver Health',
  },
  {
    plantName: 'Yashtimadhu',
    scientificName: 'Glycyrrhiza glabra',
    description: 'Sweet root - soothing herb',
    uses: 'Voice clarity, Digestive aid, Respiratory',
    imagePath: 'images/19.jpg',
    category: 'Soothing',
  },
  {
    plantName: 'Amalaki',
    scientificName: 'Emblica officinalis',
    description: 'Rejuvenator - antioxidant',
    uses: 'Rejuvenation, Immunity, Antioxidant',
    imagePath: 'images/20.jpg',
    category: 'Rejuvenation',
  },
  {
    plantName: 'Kapikacchu',
    scientificName: 'Mucuna pruriens',
    description: 'Velvet bean - nervine tonic',
    uses: 'Nervous system, Vitality, Mood management',
    imagePath: 'images/21.jpg',
    category: 'Nervine',
  },
  {
    plantName: 'Maricha',
    scientificName: 'Piper nigrum',
    description: 'Black pepper - digestive fire',
    uses: 'Digestion, Metabolism, Bioavailability',
    imagePath: 'images/22.jpg',
    category: 'Digestive',
  },
  {
    plantName: 'Shilajit',
    scientificName: 'Asphaltum punjabinum',
    description: 'Mineral pitch - energy booster',
    uses: 'Energy, Stamina, Mineral supplement',
    imagePath: 'images/23.jpg',
    category: 'Energy',
  },
  {
    plantName: 'Bilva',
    scientificName: 'Aegle marmelos',
    description: 'Wood apple - digestive tonic',
    uses: 'Digestive health, Diarrhea relief, Nutrition',
    imagePath: 'images/24.jpg',
    category: 'Digestive',
  },
  {
    plantName: 'Khadira',
    scientificName: 'Acacia catechu',
    description: 'Catechu tree - blood purifier',
    uses: 'Blood purification, Skin health, Dental care',
    imagePath: 'images/25.jpg',
    category: 'Purifier',
  },
  {
    plantName: 'Gokshura',
    scientificName: 'Tribulus terrestris',
    description: 'Puncture vine - urinary tonic',
    uses: 'Urinary health, Vitality, Kidney support',
    imagePath: 'images/26.jpg',
    category: 'Urinary Health',
  },
  {
    plantName: 'Haridra',
    scientificName: 'Curcuma longa',
    description: 'Turmeric - anti-inflammatory',
    uses: 'Anti-inflammatory, Immunity, Skin health',
    imagePath: 'images/27.jpg',
    category: 'Anti-inflammatory',
  },
  {
    plantName: 'Nimba',
    scientificName: 'Azadirachta indica',
    description: 'Neem - purifying herb',
    uses: 'Blood purification, Skin care, Antibacterial',
    imagePath: 'images/28.jpg',
    category: 'Purifier',
  },
  {
    plantName: 'Mustak',
    scientificName: 'Cyperus rotundus',
    description: 'Nut grass - digestive aid',
    uses: 'Digestive health, Menstrual health, Fever',
    imagePath: 'images/29.jpg',
    category: 'Digestive',
  },
  {
    plantName: 'Kumari',
    scientificName: 'Aloe barbadensis',
    description: 'Aloe vera - cooling herb',
    uses: 'Cooling, Skin care, Digestive health',
    imagePath: 'images/30.jpg',
    category: 'Cooling',
  },
  {
    plantName: 'Bakuchi',
    scientificName: 'Psoralea corylifolia',
    description: 'Babchi - skin health',
    uses: 'Skin disorders, Vitiligo, Hair health',
    imagePath: 'images/31.jpg',
    category: 'Skin Care',
  },
  {
    plantName: 'Devadaru',
    scientificName: 'Cedrus deodara',
    description: 'Himalayan cedar - respiratory aid',
    uses: 'Respiratory health, Pain relief, Aromatherapy',
    imagePath: 'images/33.jpg',
    category: 'Respiratory',
  },
  {
    plantName: 'Chandana',
    scientificName: 'Santalum album',
    description: 'Sandalwood - cooling fragrant',
    uses: 'Cooling, Skin care, Aromatherapy, Mental calm',
    imagePath: 'images/34.jpg',
    category: 'Cooling',
  },
];

const run = async () => {
  await connectDB(process.env.MONGODB_URI);
  const count = await Plant.countDocuments();
  if (count === 0) {
    await Plant.insertMany(samplePlants);
    console.log('🌱 Seeded sample plants');
  } else {
    console.log('🌿 Plants already exist, skipping seed');
  }
  process.exit(0);
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
